services:
  rommagic:
    image: rommagic
    container_name: rommagic
    user: "1000:1000"
    pull_policy: never
    mem_limit: "4g"
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - USER=app
    volumes:
      - /home/user/ROMs:/app/ROMs
    healthcheck:
      test: [
          "CMD-SHELL",
          "python -c \"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:5000', timeout=5).getcode()==200 else 1)\""
            ]
      interval: 30s
      timeout: 3s
      retries: 3
